name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        # Use `npm install` when no package-lock.json is committed. If you
        # prefer reproducible installs, generate and commit package-lock.json
        # locally and switch back to `npm ci`.
        run: npm install
      - name: Build
        run: npm run build --if-present
      - name: Run tests
        run: npm test --if-present
